-- INSERT INTO TB_USUARIO (DS_CPF, DS_EMAIL, DS_NOME, DS_SENHA, DT_NASCIMENTO, ID_GENERO, ID_GRUPO, IS_ATIVO)
-- VALUES
-- ('191.191.191-00', 'admin@admin.com', 'Admin', '$2a$10$cBSFq6eZvw8Bo8n/XvNP2eDfYKiMpwMRcd0MXCuhPNQsebHroaNte', '2003-11-14', 1, 1, true);

-- INSERT INTO TB_ENDERECO (DS_BAIRRO, DS_CEP, DS_CIDADE, DS_COMPLEMENTO, DS_LOGRADOURO, DS_NUMERO, DS_UF, FK_USUARIO)
-- VALUES
-- ('Centro', '12345-678', 'São Paulo', '', 'Rua das Flores', '123', 'SP', 1);